/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(guard_tagged_stream.h)                                     */
/* BINDTOOL_HEADER_FILE_HASH(c6b2f3bd74b8452d4eb7f7c02fc6804b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sprobe/guard_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <guard_tagged_stream_pydoc.h>

template<class IN_T>
void bind_guard_tagged_stream_template(py::module& m, const char* classname){

    using guard_tagged_stream = gr::sprobe::guard_tagged_stream<IN_T>;

    py::class_<
        guard_tagged_stream,
        // gr::tagged_stream_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<guard_tagged_stream>>(m, classname)
        
        .def(
            py::init(&guard_tagged_stream::make),
            py::arg("length_tag_key") = "packet_len",
            py::arg("end_tag_key") = "packet_end",
            py::arg("tail_len") = 1)
        .def("length_tag_key", &guard_tagged_stream::length_tag_key)
        .def("end_tag_key", &guard_tagged_stream::end_tag_key)
        .def("tail_len", &guard_tagged_stream::tail_len)
        .def("set_length_tag_key", &guard_tagged_stream::set_length_tag_key, py::arg("length_tag_key"))
        .def("set_end_tag_key", &guard_tagged_stream::set_end_tag_key, py::arg("end_tag_key"))
        .def("set_tail_len", &guard_tagged_stream::set_tail_len, py::arg("tail_len"));
        
}

void bind_guard_tagged_stream(py::module& m) {
    bind_guard_tagged_stream_template<gr_complex>(m, "guard_tagged_stream_c");
    bind_guard_tagged_stream_template<float>(m, "guard_tagged_stream_f");
    bind_guard_tagged_stream_template<std::uint8_t>(m, "guard_tagged_stream_b");
    bind_guard_tagged_stream_template<std::int16_t>(m, "guard_tagged_stream_s");
    bind_guard_tagged_stream_template<std::int32_t>(m, "guard_tagged_stream_i");
}
