/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(unguard_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4670575dd37d4169f3ebc10d22113ac5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sprobe/unguard_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <unguard_tagged_stream_pydoc.h>

template<class IN_T>
void bind_unguard_tagged_stream_template(py::module& m, const char* classname){

    using unguard_tagged_stream = gr::sprobe::unguard_tagged_stream<IN_T>;

    py::class_<
        unguard_tagged_stream,
        gr::block,
        gr::basic_block,
        std::shared_ptr<unguard_tagged_stream>>(m, classname)
        
        .def(
            py::init(&unguard_tagged_stream::make),
            py::arg("start_tag_name") = "packet_len",
            py::arg("end_tag_name") = "packet_end")
            
        .def("start_tag_name", &unguard_tagged_stream::start_tag_name)
        .def("end_tag_name", &unguard_tagged_stream::end_tag_name)
        .def("set_start_tag_name", &unguard_tagged_stream::set_start_tag_name, py::arg("start_tag_name"))
        .def("set_end_tag_name", &unguard_tagged_stream::set_end_tag_name, py::arg("end_tag_name"));
}

void bind_unguard_tagged_stream(py::module& m) {
    bind_unguard_tagged_stream_template<gr_complex>(m, "unguard_tagged_stream_c");
    bind_unguard_tagged_stream_template<float>(m, "unguard_tagged_stream_f");
    bind_unguard_tagged_stream_template<std::uint8_t>(m, "unguard_tagged_stream_b");
    bind_unguard_tagged_stream_template<std::int16_t>(m, "unguard_tagged_stream_s");
    bind_unguard_tagged_stream_template<std::int32_t>(m, "unguard_tagged_stream_i");
}


